Revert

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -36,7 +36,7 @@ jobs:
           echo "PCAP_SDK_DIR=C:\\WpdPack" >> $env:GITHUB_ENV
 
       - name: Set WinDivert root
-        run: echo "WINDIVERT_DIR=C:\WinDivert" >> $env:GITHUB_ENV
+        run: echo "WINDIVERT_DIR=C:\\WinDivert" >> $env:GITHUB_ENV
 
       - name: Install WinDivert
         run: ci\install_windivert.bat $env:WINDIVERT_DIR
@@ -94,13 +94,13 @@ jobs:
           Get-ChildItem Env: | Where-Object { $_.Name -match "WINDIVERT" }
 
           # Verify DLL is visible
-          # if (-not (Test-Path "C:\WinDivert\x64\WinDivert.dll")) {
-          #   Write-Error "WinDivert.dll not found in C:\WinDivert\x64"
-          #   exit 1
-          # }
+          if (-not (Test-Path "C:\WinDivert\x64\WinDivert.dll")) {
+            Write-Error "WinDivert.dll not found in C:\WinDivert\x64"
+            exit 1
+          }
           
-          Copy-Item "${{ env.WINDIVERT_DIR }}\x64\WinDivert.dll" "Tests\Pcap++Test\Bin\WinDivert.dll" -Force
-          # Copy-Item "C:\WinDivert\x64\WinDivert.dll" "Tests\Pcap++Test\Bin\WinDivert.dll" -Force
+          # Copy-Item "${{ env.WINDIVERT_DIR }}\x64\WinDivert.dll" "Tests\Pcap++Test\Bin\WinDivert.dll" -Force
+          Copy-Item "C:\WinDivert\x64\WinDivert.dll" "Tests\Pcap++Test\Bin\WinDivert.dll" -Force
 
           python -m pip install -r ci\run_tests\requirements.txt
           python ci\run_tests\run_tests_windows.py --include-tests windivert
